project:
  type: book
  # output-dir: docs

execute:
  freeze: auto
  echo: true

book:
  title: "Correlating Chromatin Compartments with Selection"
  subtitle: "How Chromatin Architecture Reflects Evolutionary Pressures During Spermatogenesis in Primates"
  author: "Søren Jørgensen"
  chapters:
    - index.qmd
    - part: "Notebooks"
      chapters: 
      - notebooks/01_weather.ipynb
      - notebooks/02_interaction.ipynb
    - part: "Reports"
      chapters: 
      - reports/manuscript.ipynb
      - reports/supplementary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - default
      - custom.scss
    toc-depth: 2
    notebook-links: global
    number-sections: false

