project:
  type: book
  post-render: 
    - quarto render --profile slides

execute:
  freeze: auto
  echo: true

format:
  html:
    theme: 
      - default
      - custom.scss
    toc-depth: 2
    notebook-links: global
    number-sections: false

comments:
  hypothesis: true


book:
  repo-url: "https://github.com/munch-group/hic-spermatogenesis"
  repo-actions: [edit, issue, source]  
  title: "Søren's MSc project about Hi-C and spermatogenesis"
  author: "Søren Jørgensen"
  chapters:
    - index.qmd
    - thoughts.qmd
    - part: "Notebooks"
      chapters: 
      - notebooks/001_weather.ipynb
      - notebooks/002_interaction.ipynb
      - notebooks/01_hicexplorer.ipynb
      - notebooks/02_open2c_framework.ipynb
    - part: "Workflows"
      chapters:
      - gwf_map_reads.py
      - gwf_bowtie.py
      - gwf_bowtie_local.py
      - gwf_hiccorrect.py
      - gwf_bwamem.py
      - gwf_pair_alignments.py
    - part: "Reports"
      chapters: 
      - results/Readme.md
      - reports/manuscript.ipynb
      - reports/supplementary.qmd
    - part: "Slides"
      chapters:
      # markdown slides
      # (the same files must be listed _quarto-slides.yml to render as slides)
      - slides/slides.qmd 
      - slides/suppl_slides.qmd 
    - references.qmd

bibliography: references.bib
