project:
  type: book
  # output-dir: docs
  preview:
    port: 4202

execute:
  freeze: auto
  echo: true

book:
  title: "Søren's MSc project about Hi-C and spermatogenesis"
  author: "Søren Jørgensen"
  chapters:
    - index.qmd
    - thoughts.qmd
    - part: "Notebooks"
      chapters: 
      - notebooks/001_weather.ipynb
      - notebooks/002_interaction.ipynb
      - notebooks/01_hicexplorer.ipynb
      - notebooks/02_open2c_framework.ipynb
    - part: "Workflows"
      chapters:
        - gwf_map_reads.py
        - gwf_bowtie.py
        - gwf_bowtie_local.py
        - gwf_hiccorrect.py
        - gwf_bwamem.py
        - gwf_pair_alignments.py
    - part: "Reports"
      chapters: 
      - results/Readme.md
      - reports/manuscript.ipynb
      - reports/supplementary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - default
      - custom.scss
    toc-depth: 2
    notebook-links: global
    code-links: repo
    number-sections: false

