project:
  type: book
  post-render:
    - quarto render --profile slides
  preview:
    port: 4201
execute:
  freeze: auto
  echo: true

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    grid:
      sidebar-width: 210px
      margin-width: 150px
    toc-depth: 2
    notebook-links: global
    number-sections: false

comments:
  hypothesis: true


book:
  repo-url: "https://github.com/munch-group/hic-spermatogenesis"
  repo-actions: [edit, issue, source]  
  title: "Søren's MSc project about Hi-C and spermatogenesis"
  author: "Søren Jørgensen"
  sidebar:
    collapse-level: 1
    reader-mode: true
  chapters:
    - index.qmd
    - thoughts.qmd
    - part: "Notebooks"
      chapters: 
      #- notebooks/001_weather.ipynb
      #- notebooks/002_interaction.ipynb
      - notebooks/01_hicexplorer.ipynb
      - notebooks/02_open2c_framework.ipynb
      - notebooks/03_compartments.ipynb
    - part: "Workflows"
      chapters:
      - master_workflow.py
      - gwf_map_reads.py
      - gwf_bowtie.py
      - gwf_bowtie_local.py
      - gwf_hiccorrect.py
      - gwf_bwamem.py
      - gwf_pair_alignments.py
    - part: "Reports"
      chapters: 
      #- results/Readme.md
      #- reports/manuscript.ipynb
      #- reports/supplementary.qmd
      - reports/manus/main.qmd
      - reports/manus/supplementary.qmd
    - part: "Slides"
      chapters:
      # markdown slides
      # (the same files must be listed _quarto-slides.yml to render as slides)
      - slides/slides.qmd 
      - slides/suppl_slides.qmd 
    - references.qmd

bibliography: references.bib
