
format:
  clean-revealjs:
    smaller: true

execute:
  freeze: auto
  echo: false

project:
  output-dir: _book
  render:
    - slides/project_progress.qmd
    #- slides/slides.qmd
    #- slides/suppl_slides.qmd

