---
title: "Project"
#bibliography: references.bib
date: last-modified
date-format: "MMMM D, YYYY <br> HH:mm:ss (UTC Z)"
---

# Project {.unnumbered}

- Visit the [project guide](ttps://munch-group.org/project-guide/) for help.
- Visit Open Chromosome Collective ([Open2C](https://github.com/open2c/)) for tools and tutorials on 3D Chromosome biology
- Visit [HiCExplorer docs](https://hicexplorer.readthedocs.io/en/latest/)
- Raw data from [@wang_reprogramming_2019] can be download [here](https://www.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA430777&o=acc_s%3Aa), but requires [`SRA toolkit`](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit)


## Outline

Hi-C data is often generated for whole-genome sequencing (WGS) and the assembly of genomes due to its ability to capture the three-dimensional organization of the genome. This spatial information helps in correctly assembling contigs into chromosomes by providing contacts between distant genomic regions, thus resolving ambiguities in the linear sequence data. Thus, Hi-C data is often available, and leveraging this existing data can provide valuable insights to other areas without the need for additional sequencing. The aim of this project is to analyze chromatin compartments on the X chromosome during spermatogenesis in baboons, macaques, and humans using Hi-C data. The project involves generating interaction maps and identifying PC1 compartments. A key objective is to compare transition zones with regions undergoing positive selection to uncover how chromatin architecture reflects evolutionary pressures. The ultimate goal is to deepen our understanding of chromatin organization and the conservation of non-advantageous alleles, providing insights into the role of selfish genes in shaping genome evolution.

## Notes on litterature as I read it

[@wang_reprogramming_2019] Macaque/Mouse Hi-C paper. They use HiC-Pro and incorporates RNAseq data analyzed by TopHat and CuffLinks. Introduce small-scale *in situ* Hi-C (sisHi-C). They analyze both A/B compartments and TADs. Also introduce 'Refined A/B compartments' with 'Local PCA'. They cite [@servant_hic_pro_2015] for their PCA method. 

[@servant_hic_pro_2015] describes the software [`HiC-Pro`](https://github.com/nservant/HiC-Pro). Is a pipeline for all the steps until analysis of the contact maps. Includes (iterative correction) normalization steps, which is also available as standalone [`hiclib`/`iced`](https://github.com/hiclib/iced) tool. They refer to [@lieberman_aiden_comprehensive_2009] for PCA method.

[@lieberman_aiden_comprehensive_2009] Introduces the Hi-C method and some ways of analyzing the data. E.g. the eigenvector (PCA) method, where they refer back to [@price_principal_2006]

[@price_principal_2006] use PCA to account for stratification in GWAS. The paper was cited by the Hi-C paper (2009) which was cited by the HiC-Pro paper as their PCA method. No real use for this paper, and they also refer back to a general guide on PCA from 2003. *End of citation chain*. 

[@zuo_stage_resolved_2021] Stage-resolved Hi-C analysis in **mouse spermatogenesis**, using mm10 reference genome. They use [`hiclib`](https://github.com/mirnylab/hiclib-legacy) (now replaced by [`distiller`](https://github.com/open2c/distiller-nf)) and [`cooler`](https://github.com/open2c/cooler)/[`cooltools`](https://github.com/open2c/cooltools) from mirnylab. They focus on **genome-wide** chromatin structure, especially the weakening of TADs in prophase I (pachytene stage) while there is persistent CTCF binding (loops). They suggest that chromosome organization may provide an infrastructure for the modulation of meiotic recombination in higher eukaryotes. 

> **Q:** Could alterations in TAD organization during specific meiotic stages create opportunities for selfish genes to proliferate or influence transmission?

[@batra_accurate_2020] Baboon paper. They announce a new *de novo*-assembled reference genome, *Panubis1.0*, more accurate than the previous *Panu3.0*, which was a highly fragmented assembly based on short-read seq-tech and reference guided assembly (ref: *rhesus macaque*). They made the *de novo* assembly by combining 10x Genomics (physically linked short-reads) with Nanopore long-reads, and finally ordering and orienting the reads with Hi-C seq. They state no specific conclusions about the Hi-C data separate from the assemmbly.  

[@shami_single_cell_2020] Divergent features of mammalian spermatogenesis. They use scRNA-seq to study spermatogenesis in human, macaque, mice. They compare conserved and divergent features of spermatogenesis across species. Spermatogonia, spermatocytes, spermatids. Identified a gene *TSPAN33* that was expressed in primate spermatogonia populations, but not in mice. They found both conserved patterns across species and species-specific patterns, notably in genes involved in immune system and blood-testis barrier, also including signalling pathways. Identify a genetic region that may be of interest, but otherwise I don't know how to use this paper, unless they have Hi-C data they can send us. 

[@chakraborty_dchic_2022] dcHiC paper/[`dcHiC` tool](https://github.com/ay-lab/dcHiC). Differential compartments analysis. Utilize a multivariate distance measure, Mahalanobis (opposed to only pairwise comparisons) to identify and analyze changes across multiple Hi-C maps. They found compartmental changes in regions containing genes involved in cell identity (regulating pluripottency, cell adhesion, signaling pathways) during neuronal development. `dcHiC` can also identify sub-compartmental changes, and integrate compartmentalization data from other datasets (gene expression, histone modification, replication timing). Multivariata seems to be a better way of considering the Hi-C data. 

[@bicciato_hic_2022] Book on Hi-C data analysis. Might use to find conventional use of thresholds, etc. Might follow a couple of these pipelines if they are not already outdated. 

[@skov_extraordinary_2023] Paper from Munch-group. *Cautiously* hypothesize that meiotic drive on X chr could be responsible for their observations. Examining the selective sweeps in the context of (primate) spermatogenesis could be insightful. Integrating gene expression and Hi-C maps during spermatogenesis, could potentially uncover if the sweeps preferentially affect active elements/gene during spermatogenesis at i.e. specific stages. 

[@nunez_genetic_2018]. Paper on Genetic Villains/meiotic drivers. Describes the difficulty of detecting drive, and different types of drive. Killer-Target, Poison-Antidote. They have nice illustrations of meiotic drive. 

[@HiC_human_cancer_2021] Most recent paper I could find on Hi-C in human. But it is about cancer and other omics than Hi-C.

## Schedule / Work plan

**Semester:** Monday, Aug 26th – Wednesday, Jan 15th (Week 35-3)\
**Hand-in:** Wednesday, Jan 15th (Week 3)\
**Holiday:** Wednesday, Oct 23rd – Monday, Oct 28th (Week 43)\
**Christmas Holidays:** Monday, Dec 23rd – Friday, Jan 3rd (Week 52-1)\

**Week 35-36 (Aug 26 - Sep 7):**\
Conduct a literature review on chromatin architecture, Hi-C methodology, and the concept of selfish genes. Get an overview of (and obtain) data sets to be used.

**Week 37-38 (Sep 9 - Sep 21):**\
Assess the status of existing Hi-C data (raw or QC’ed). If necessary, perform initial quality control. Align reads to reference genomes.

**Week 39-40 (Sep 23 - Oct 5):**\
Process Hi-C interaction data. Perform quality assessment.

**Week 41-42 (Oct 7 - Oct 19):**\
Generate and normalize interaction matrices for the X chromosome.

**Week 43 (Oct 21 - Oct 26):**\
Holiday from Wednesday (no major activities planned). Tidy notes and do some writing.

**Week 44-45 (Oct 28 - Nov 9):**\
Perform PCA to obtain PC1 compartments. Visualize results.

**Week 46-47 (Nov 11 - Nov 23):**\
Identify A/B compartment transitions. Overlay with positive selection regions.

**Week 48-49 (Nov 25 - Dec 7):**\
Conduct cross-species analysis by converting genomic coordinates.

**Week 50 (Dec 9 - Dec 14):**\
Finish analyses. Compare results.

**Week 51 (Dec 16 - Dec 21):**\
Finalize analyses and begin writing initial thesis draft, incorporating analysis results and discussions.

**Week 52 (Dec 23 - Dec 28):**\
Christmas holidays (no major activities planned). Will work a couple of days Dec 27-29.

**Week 1 (Dec 30 - Jan 4):**\
Christmas holidays until Jan 2 (just performing modifications to analyses, etc.).

**Week 2 (Jan 6 - Jan 11):**\
Revise thesis draft based on feedback. Continue refinement of analyses if necessary.

**Week 3 (Jan 13 - Jan 15):**\
Final revisions and hand-in on Wednesday, January 15th.

