format:
  clean-revealjs:
    smaller: false
    toc: false
    toc-title: "Overview"
    toc-depth: 2
    width: 1080
    height: 720
    margin: 0.05
    logo: aulogo_uk_var2_blue.png
    footer: "<em>Chromatin Architecture and Selection on X &nbsp; • &nbsp; Søren Jørgensen &nbsp; • &nbsp; MSc. Bioinformatics  &nbsp; • &nbsp; munch-group.org/hic-spermatogenesis </em> &nbsp;&nbsp;&nbsp;&nbsp;"
    include-after-body: clean_title_page.html
    history: false
    auto-animate-unmatched: false
    auto-animate-duration: 0.3

execute:
  freeze: auto
  echo: false

project:
  output-dir: ../_book/slides
  render:
    - index.qmd
    - midterm_progress.qmd
    - defence.qmd

bibliography: ../references.bib

