project:
  type: manuscript
  title: "Thesis"
  output-dir: ../_book/thesis
  pre-render: [ -f ../_book/thesis/_tex/sub-references.bib ] && rm ../_book/thesis/_tex/sub-references.bib
 # I don't know why this is not auto-cleaned when keep-tex:false
  # post-render: mv -v ../_book/thesis/_tex/index.tex ../_book/thesis/_tex/manuscript.tex # for debugging (coupled with `keep-tex: true` in the format section)

manuscript:
  article: index.qmd

format:
  html: default
  #docx: default
  jats: default
  pdf:
    pdf-engine-opts: # mandatory to render svg images (as well as `inkscape` in $PATH)
      - "--shell-escape"
    documentclass: scrartcl
    # keep-tex: true # for debugging (coupled with renaming in the post-render script)
    dpi: 320
    papersize: a4
    toc: true
    toc-depth: 2
    highlight-style: kate 
    shift-heading-level-by: -1
    number-sections: true
    number-depth: 3
    colorlinks: false
    geometry: 
      - textheight=9in
      - textwidth=6.5in
      - top=1in
      - headheight=14pt
      - headsep=25pt
      - footskip=30pt   
    cite-method: natbib 
    #natbiboptions: numbers
    include-in-header:
      - file: header_extra.tex
      - file: preamble.tex
    include-before-body:
      - text: |
          \newpage
          \tableofcontents
    output-file: manuscript.pdf

notebook-links: false

execute:
  freeze: auto

bibliography: sub-references.bib