project:
  type: manuscript
  output-dir: ../_book/thesis
  # Fix the preview port-forwarding so it doesn't open a new tab each time (and stops forwarding ports)
  preview:
    port: 4202

manuscript:
  article: index.qmd

format:
  html: default
  docx: default
  jats: default

  pdf:
    # latex-clean: false
    documentclass: scrbook
    pdf-engine: pdflatex
    cite-method: natbib
    #natbiboptions: numbers
    papersize: A4
    toc: true
    toc-depth: 2
    toc-title: "Table of contents"
    lof: false
    lot: false    
    geometry:
      - left=2.54cm
      - right=2.54cm           
      # - inner=3cm
      # - outer=4cm
      # - top=3cm
      # - bottom=4cm
      # - headsep=22pt
      # - headheight=11pt
      # - footskip=33pt
      # - ignorehead
      # - ignorefoot
      # - heightrounded
    fontsize: 11pt
    linestretch: 1.2
    number-sections: true
    number-depth: 2
    highlight-style: kate 
    tbl-cap-location: top
    include-in-header:
      - file: header_extra.tex
    template-partials:
      - before-body.tex      

notebook-links: false

lightbox: true

execute:
  freeze: auto

bibliography: ../references.bib